# React CI/CD Pipeline Configuration Example
# This file shows all available React-specific configuration options

# Project Configuration
project_language: react
# Note: Pipeline now uses npm by default (packageManager setting removed for simplicity)

# Node.js Version Configuration
react_version: "18"  # Node.js version for React projects
# nodejs_version: "18"  # Alternative for pure Node.js projects

# Docker Configuration
nexus:
  url: "https://nexus.company.com:8082"
  registry: "nexus.company.com:8082"
  project: "dev"
  credentials_id: "nexus-docker-creds"



# Stage Execution Control
runUnitTests: true
runLintTests: true
runFunctionalTests: true
runSmokeTests: true
runSanityTests: true
runRegressionTests: true

# Tool Configuration
tool_for_unit_testing:
  react: jest  # Options: jest, react-testing-library, cypress

tool_for_lint_testing:
  react: eslint  # Options: eslint, prettier, tslint

# React-Specific Tool Versions (Optional)
tools:
  jest: "^29.0.0"
  eslint: "^8.0.0"
  prettier: "^2.8.0"
  typescript: "^4.9.0"

# Basic Notification Configuration
notifications:
  email:
    recipients: 
      - "smanprit022@gmail.com"
  slack:
    enabled: false           # Set to true when you get Slack access
    channel: "#builds


